
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("900x520")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 520,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    451.0,
    260.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    351.0,
    521.4857177734375,
    fill="#C3DD8C",
    outline="")

canvas.create_text(
    30.0,
    44.0,
    anchor="nw",
    text="ELIXIR-Nature magic at its best",
    fill="#2B962F",
    font=("Inter Bold", 23 * -1)
)

canvas.create_rectangle(
    378.0,
    41.0,
    627.0,
    483.0,
    fill="#C3DD8D",
    outline="")

canvas.create_rectangle(
    389.0,
    95.0,
    609.0,
    95.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    409.0,
    59.0,
    anchor="nw",
    text="MEDICAL",
    fill="#2B9730",
    font=("Inter Light", 24 * -1)
)

canvas.create_rectangle(
    654.0,
    42.0,
    889.0,
    266.0,
    fill="#C3DD8D",
    outline="")

canvas.create_rectangle(
    670.0,
    94.0,
    873.0,
    96.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    671.0,
    59.0,
    anchor="nw",
    text="ANIMAL",
    fill="#2B9730",
    font=("Inter Light", 24 * -1)
)

canvas.create_rectangle(
    664.0,
    289.0,
    889.0,
    483.0,
    fill="#C3DD8D",
    outline="")

canvas.create_rectangle(
    677.0,
    328.0,
    873.0,
    328.0,
    fill="#FFFFFF",
    outline="")

def window_1():
        window = Tk()

        window.geometry("919x548")
        window.configure(bg = "#FFFFFF")


        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 548,
            width = 919,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            919.0,
            548.0,
            fill="#C3DD8C",
            outline="")

        canvas.create_text(
            34.0,
            58.0,
            anchor="nw",
            text="Stomach ache",
            fill="#597D0C",
            font=("Gluten Medium", 32 * -1)
        )

        canvas.create_text(
            30.0,
            146.0,
            anchor="nw",
            text=''' 
            Rock salt is salt in its purest form. It's much better than the white salt that we normally consume as it's loaded with natural 
            minerals and aids in digestion.Rock salt when taken with lemon juice helps to relieve gases in the digestive tract and system. We 
            burp and pass out the gasses. It relieves the bloated stomach," 

            Word of caution - Rock salt and lemon juice provide relief only in mild cases. A severe attack of gastroenteritis, for instance, will not 
            be cured by the concoction.Heart and high BP patients should be cautious, for they are advised to eat less salt. Although rock salt 
            might be natural, its effects are similar to that of normal salt
            ''',
            fill="#384B0F",
            font=("Taviraj Regular", 16 * -1)
        )

        image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = canvas.create_image(
            738.0,
            274.0,
            image=image_image_1
        )

        canvas.create_text(
            628.0,
            484.0,
            anchor="nw",
            text="ROCK SALT WITH LEMON",
            fill="#C03D6C",
            font=("Gluten Regular", 18 * -1)
        )

        canvas.create_rectangle(
            31.0,
            117.0,
            521.0,
            118.0,
            fill="#FFFFFF",
            outline="")
        window.resizable(False, False)
        window.mainloop()
    


button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=window_1,
    relief="flat"
)
button_1.place(
    x=407.0,
    y=131.0,
    width=201.0,
    height=38.0
)
def window_7():
        window = Tk()

        window.geometry("919x584")
        window.configure(bg = "#FFFFFF")


        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 584,
            width = 919,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            919.0,
            584.0,
            fill="#C3DD8D",
            outline="")

        canvas.create_text(
            37.0,
            48.0,
            anchor="nw",
            text="Dehydration",
            fill="#597D0D",
            font=("Gluten Medium", 32 * -1)
        )

        canvas.create_rectangle(
            41.0,
            91.0,
            853.0,
            96.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            49.0,
            124.0,
            anchor="nw",
            text="How to tell if any animal is dehydrated?",
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            49.0,
            164.0,
            anchor="nw",
            text="The signs of dehydration in animals to look out for include:",
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            49.0,
            205.0,
            anchor="nw",
            text=">Sunken eyes",
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            49.0,
            245.0,
            anchor="nw",
            text=">Dry gums",
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            49.0,
            285.0,
            anchor="nw",
            text=">Lethargy",
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            49.0,
            326.0,
            anchor="nw",
            text=">Weakness",
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            49.0,
            366.0,
            anchor="nw",
            text=">Collapse",
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            49.0,
            407.0,
            anchor="nw",
            text=">Loss of skin elasticity",
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            49.0,
            447.0,
            anchor="nw",
            text="The most effective way of treating dehydration is to place the pet on a drip. This will replace any fluids already lost and also prevent further dehydration.",
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            49.0,
            528.0,
            anchor="nw",
            text="Oral rehydration solutions can also be used.",
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )
        window.resizable(False, False)
        window.mainloop()

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=window_7,
    relief="flat"
)
button_2.place(
    x=672.0,
    y=117.0,
    width=201.0,
    height=38.0
)
def window_8():
    
        window = Tk()

        window.geometry("919x584")
        window.configure(bg = "#FFFFFF")


        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 584,
            width = 919,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            919.0,
            584.0,
            fill="#C3DD8D",
            outline="")

        canvas.create_text(
            36.0,
            45.0,
            anchor="nw",
            text="Nauseous Animals",
            fill="#597D0D",
            font=("Gluten Medium", 32 * -1)
        )

        canvas.create_rectangle(
            25.0,
            87.99629974365234,
            839.0,
            89.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            45.0,
            124.0,
            anchor="nw",
            text='''
            Oral antacids in syrup base or tablet form Such as Digene or Mucain that can be given to the dog 
            using a 5/10ml syringe-squirting directly into the mouth at 5ml for 20kg. This can be used 4-5 
            times a day. This works well if there mild indigestion or acidity etc. The best would be to keep dog 
            antacids like Digyton Drops handy at home.
            ''',
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            45.0,
            284.0,
            anchor="nw",
            text='''
            Himalaya Liv. 52 protects the liver from toxins, drugs and chemicals. Regeneration of liver cells: 
            The drug restores the architecture and function of the damaged liver by promoting the regeneration of liver cells. 
            Promotes protein synthesis: It enhances protein building in liver cells.
            ''',
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            45.0,
            443.0,
            anchor="nw",
            text='''
            You can give small amount of this syrup to your pet daily for their healthy living.
            ''',
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )
        window.resizable(False, False)
        window.mainloop()

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=window_8,
    relief="flat"
)
button_3.place(
    x=671.0,
    y=162.0,
    width=201.0,
    height=38.0
)
def window_9():
    
        window = Tk()

        window.geometry("919x584")
        window.configure(bg = "#FFFFFF")


        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 584,
            width = 919,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            919.0,
            584.0,
            fill="#C3DD8D",
            outline="")

        canvas.create_text(
            41.0,
            61.0,
            anchor="nw",
            text="Pain",
            fill="#597D0D",
            font=("Gluten Medium", 32 * -1)
        )

        canvas.create_text(
            35.0,
            125.0,
            anchor="nw",
            text='''
            The importance of pain management and the use of nonsteroidal anti-inflammatory drugs (NSAIDs) 
            in animals has increased dramatically in recent decades, and use of NSAIDs in companion animals is 
            routine practice.
            ''',
            fill="#384B0F",
            font=("Taviraj Medium", 16 * -1)
        )

        canvas.create_text(
            38.0,
            188.0,
            anchor="nw",
            text='''
            NSAIDs have the potential to relieve pain and inflammation without the myriad potential metabolic, 
            hemodynamic, and immunosuppressive adverse effects associated with corticosteroids.
            ''',
            fill="#384B0F",
            font=("Taviraj Medium", 16 * -1)
        )

        canvas.create_text(
            38.0,
            272.0,
            anchor="nw",
            text='''
            Aceclofenac is a nonsteroidal anti-inflammatory drug which can be given to animals in proper proportions.
            ''',
            fill="#384B0F",
            font=("Taviraj Medium", 16 * -1)
        )

        canvas.create_text(
            35.0,
            320.0,
            anchor="nw",
            text='''
            Adult dogs : 1|2 tablet twice a day.\nPuppies and Feline friends : 1|4 tablet twice day.
            ''',
            fill="#384B0F",
            font=("Taviraj Medium", 16 * -1)
        )

        canvas.create_text(
            38.0,
            391.0,
            anchor="nw",
            text='''
            || When you find an animal suffering please be kind enough to give him\her shelter and 
            proper medications and take care till they are healthy enough ||
            ''',
            fill="#384B0F",
            font=("Gluten Medium", 18 * -1)
        )

        canvas.create_text(
            198.0,
            503.0,
            anchor="nw",
            text="#ADOPT, DONT SHOP",
            fill="#000000",
            font=("Gluten SemiBold", 18 * -1)
        )

        canvas.create_rectangle(
            32.0,
            95.0,
            865.0,
            97.0,
            fill="#FFFFFF",
            outline="")
        window.resizable(False, False)
        window.mainloop()

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=window_9,
    relief="flat"
)
button_4.place(
    x=672.0,
    y=215.0,
    width=201.0,
    height=38.0
)
def window_10():
        window = Tk()

        window.geometry("919x584")
        window.configure(bg = "#FFFFFF")


        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 584,
            width = 919,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            919.0,
            584.0,
            fill="#C3DD8D",
            outline="")

        canvas.create_text(
            37.0,
            50.0,
            anchor="nw",
            text="Chicken Curry Soup",
            fill="#597D0D",
            font=("Gluten Medium", 32 * -1)
        )

        canvas.create_text(
            44.0,
            135.0,
            anchor="nw",
            text='''
            Curry contains a variety of anti-inflammatory spices, including turmeric, coriander, and chili 
            powder.
            ''',
            fill="#384B0F",
            font=("Taviraj Medium", 17 * -1)
        )

        canvas.create_text(
            44.0,
            211.0,
            anchor="nw",
            text='''
            Consuming curry may benefit heart health by reducing heart disease risk factors like high 
            cholesterol and triglyceride levels and by improving blood flow.
            ''',
            fill="#384B0F",
            font=("Taviraj Medium", 17 * -1)
        )

        canvas.create_text(
            41.0,
            274.0,
            anchor="nw",
            text='''
            Some research suggests that consuming curry powder may help reduce oxidative stress, 
            thus lowering disease risk.''',
            fill="#384B0F",
            font=("Taviraj Medium", 17 * -1)
        )

        canvas.create_text(
            44.0,
            343.0,
            anchor="nw",
            text='''
            Consuming curry may boost brain and digestive health, improve feelings of fullness, 
            lower blood sugar levels, and provide antibacterial effects.
            ''',
            fill="#384B0F",
            font=("Taviraj Medium", 17 * -1)
        )

        canvas.create_rectangle(
            42.0,
            93.97235870361328,
            848.9999389648438,
            96.0,
            fill="#FFFFFF",
            outline="")
        window.resizable(False, False)
        window.mainloop()

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=window_10,
    relief="flat"
)
button_5.place(
    x=671.0,
    y=337.0,
    width=201.0,
    height=38.0
)
def window_11():
        window = Tk()

        window.geometry("919x584")
        window.configure(bg = "#FFFFFF")


        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 584,
            width = 919,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            919.0,
            584.0,
            fill="#C3DD8D",
            outline="")

        canvas.create_text(
            37.0,
            48.0,
            anchor="nw",
            text="Immunity kaadha",
            fill="#597D0D",
            font=("Gluten Medium", 32 * -1)
        )

        canvas.create_rectangle(
            41.0,
            94.0,
            848.0000610351562,
            96.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            49.0,
            124.0,
            anchor="nw",
            text='''
            As the world is under a constant threat of Covid-19 pandemic, health experts are time and again
            insisting on boosting our immunity.
            ''',
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            49.0,
            205.0,
            anchor="nw",
            text='''
            Speaking about kadha, it will not be an exaggeration if we term it to be one of the oldest 
            and treasured medicinal secrets of India. It is basically a mix of various traditional herbs 
            and spices that help us to keep strong from within.
            ''',
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            48.0,
            314.0,
            anchor="nw",
            text='''
            >Ginger- 1 inch
            | Raw turmeric- 1 inch
            | Tulsi- 8-10
            | Mulethi- 4-5 sticks
            | Cinnamon- 4-5 
            Black pepper- 10-12
            | Cloves- 10-12
            | Water- 8-10 cups
            >Boil it for at least 1 hour
            >You may also add some green tea, lemon and honey
            while warming this kadha for consumption.
        ''',
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            512.0,
            506.0,
            anchor="nw",
            text="",
            fill="#000000",
            font=("Taviraj", 18 * -1)
        )
        window.resizable(False, False)
        window.mainloop()


button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=window_11,
    relief="flat"
)
button_6.place(
    x=674.0,
    y=386.0,
    width=201.0,
    height=38.0
)
def window_2():
        window = Tk()

        window.geometry("919x584")
        window.configure(bg = "#FFFFFF")


        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 584,
            width = 919,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            919.0,
            584.0,
            fill="#C3DD8D",
            outline="")

        canvas.create_text(
            41.0,
            54.0,
            anchor="nw",
            text="Cough",
            fill="#597D0D",
            font=("Gluten Medium", 32 * -1)
        )

        canvas.create_rectangle(
            36.0,
            92.0,
            543.0,
            92.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            28.0,
            117.0,
            anchor="nw",
            text='''There is no known cure for common cold, as the virus in the body needs to live its course. A remedy is only symptomatic
            treatment for common cold.''',
            fill="#384B0F",
            font=("Taviraj", 16 * -1)
        )

        canvas.create_text(
            24.0,
            195.0,
            anchor="nw",
            text='''Garlic contains the compound allicin, which may have antimicrobial properties. Adding a garlic supplement to your diet
            might reduce the severity of cold symptoms. It might even help you avoid getting sick in the first place.''',
            fill="#384B0F",
            font=("Taviraj", 16 * -1)
        )

        canvas.create_text(
            26.0,
            315.0,
            anchor="nw",
            text='''Ginger, when boiled in water and then laced with honey, is a known
            cure for cough and sore throat.Ginger is a known cough suppressant. It is also an 
            antioxidant that provides relief from the ailment. This, along with honey, helps alleviate 
            the inflammation of the throat. The honey given its high viscosity soothes the lining of the throat''',
            fill="#384B0F",
            font=("Taviraj", 16 * -1)
        )

        canvas.create_text(
            28.0,
            477.0,
            anchor="nw",
            text='''Word of caution :Diabetics need to be careful about the amount of honey they take,
            as it might affect their sugar levels more than it would affect non-diabetics''',
            fill="#384B0F",
            font=("Taviraj", 16 * -1)
        )
        window.resizable(False, False)
        window.mainloop()


button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=window_2,
    relief="flat"
)
button_7.place(
    x=402.0,
    y=189.0,
    width=201.0,
    height=38.0
)
def window_3():
        window = Tk()

        window.geometry("919x584")
        window.configure(bg = "#FFFFFF")


        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 584,
            width = 919,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            919.0,
            584.0,
            fill="#C3DD8D",
            outline="")

        canvas.create_text(
            41.0,
            54.0,
            anchor="nw",
            text="Body aches/Pain",
            fill="#597D0D",
            font=("Regular", 32 * -1)
        )

        canvas.create_rectangle(
            43.0,
            96.0,
            652.0,
            97.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            27.0,
            121.0,
            anchor="nw",
            text='''
            Turmeric boiled in milk is an excellent combination. Milk is a good source of protein, which help to heal wounds. 
            Turmeric is known for its anti-inflammatory properties that help to soothe the inflamed muscles
            ''',
            fill="#384B0F",
            font=("Taviraj", 16 * -1)
        )

        canvas.create_text(
            27.0,
            217.0,
            anchor="nw",
            text='''
            Word of caution - Turmeric milk is effective, but only for non-serious aches and pains..At best, this can be used 
            alongside some other medically proven therapies.
            ''',
            fill="#384B0F",
            font=("Taviraj", 16 * -1)
        )

        canvas.create_text(
            41.0,
            312.0,
            anchor="nw",
            text='''
            Along with stretching, another of the important muscle cramp remedies is heat application. Applying heat 
            soon after spasming starts can help soothe the pain that comes with muscle cramp since it helps the muscle 
            loosen up. To do this, you can take a warm bath or shower. You can also apply a heating pad or a warm towel 
            directly to the tense muscle.
            ''',
            fill="#384B0F",
            font=("Taviraj", 16 * -1)
        )

        canvas.create_text(
            27.0,
            471.0,
            anchor="nw",
            text='''
            Drinking fluids while you have a cramp helps the muscles contract and relax. When you keep hydrated, your 
            muscle cells also stay hydrated and are less irritable or uncomfortable.
            ''',
            fill="#384B0F",
            font=("Taviraj", 16 * -1)
        )
        window.resizable(False, False)
        window.mainloop()

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=window_3,
    relief="flat"
)
button_8.place(
    x=402.0,
    y=247.0,
    width=201.0,
    height=38.0
)
def window_4():
        window = Tk()

        window.geometry("919x584")
        window.configure(bg = "#FFFFFF")


        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 584,
            width = 919,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            919.0,
            584.0,
            fill="#C3DD8D",
            outline="")

        canvas.create_text(
            31.99999999999997,
            43.0,
            anchor="nw",
            text="Ranger on the Rescue- 'Onion'",
            fill="#597D0D",
            font=("Gluten Medium", 32 * -1)
        )

        canvas.create_rectangle(
            32.99999999999997,
            80.0,
            874.0,
            83.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            32.99999999999997,
            129.0,
            anchor="nw",
            text='''
            Onions have long been touted as a cure-all by many cultures over the years. From Middle Eastern traditional 
            medicine prescribing them for things like diabetes to 20th-century medicine recommending them for respiratory 
            and digestive problems, the onion has been an unsung hero for too long.
            ''',
            fill="#384B0F",
            font=("Taviraj", 16 * -1)
        )

        canvas.create_text(
            32.99999999999997,
            293.0,
            anchor="nw",
            text='''
            Studies have shown that onions contain thiosulfinates (these also cause their distinctive smell) that are known 
            to reduce diabetes symptoms and protect against cardiovascular disease.
            ''',
            fill="#384B0F",
            font=("Taviraj", 16 * -1)
        )

        canvas.create_text(
            32.99999999999997,
            402.0,
            anchor="nw",
            text='''
            They also contain Quercetin, a flavonoid found in onions, which is known to prevent the inflammation associated 
            with allergies and also protects against stomach ulcers and colon, esophageal, and breast cancers. You should 
            always consult your medical professional for the best form of treatment.
            ''',
            fill="#384B0F",
            font=("Taviraj", 16 * -1)
        )
        window.resizable(False, False)
        window.mainloop()



button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=window_4,
    relief="flat"
)
button_9.place(
    x=407.0,
    y=308.0,
    width=201.0,
    height=38.0
)
def window_5():
        window = Tk()

        window.geometry("919x584")
        window.configure(bg = "#FFFFFF")


        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 584,
            width = 919,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            919.0,
            584.0,
            fill="#C3DD8D",
            outline="")

        canvas.create_text(
            51.0,
            51.0,
            anchor="nw",
            text="Nausea",
            fill="#597D0D",
            font=("Gluten Medium", 32 * -1)
        )

        canvas.create_rectangle(
            55.0,
            98.0,
            540.0,
            100.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            46.0,
            117.0,
            anchor="nw",
            text='''
            Ginger has long been known for its ability to alleviate the symptoms of nausea. From general symptoms 
            to seasickness eating some ginger will put you right.
            ''',
            fill="#384B0F",
            font=("Taviraj", 17 * -1)
        )

        canvas.create_text(
            46.0,
            215.0,
            anchor="nw",
            text='''
            Anyone who has actually tried it will be happy to hear that studies have shown that ginger is actually 
            highly effective for reducing symptoms of nausea and preventing vomiting.
            ''',
            fill="#384B0F",
            font=("Taviraj", 17 * -1)
        )

        canvas.create_text(
            46.0,
            313.0,
            anchor="nw",
            text='''
            A study in 2000 , actually found that ginger was as effective as metoclopramide which is a pharmaceutical 
            often used to relieve the same symptoms in patients.
            ''',
            fill="#384B0F",
            font=("Taviraj", 17 * -1)
        )

        canvas.create_text(
            46.0,
            411.0,
            anchor="nw",
            text='''
            Other studies support the time-old remedy as an effective and inexpensive treatment for nausea and 
            vomiting. It is a safe and readily available supportive treatment to use, but check it to use with your 
            prescribed medicine with your doctor.
            ''',
            fill="#384B0F",
            font=("Taviraj", 17 * -1)
        )
        window.resizable(False, False)
        window.mainloop()

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=window_5,
    relief="flat"
)
button_10.place(
    x=402.0,
    y=373.0,
    width=201.0,
    height=38.0
)
def window_6():
        window = Tk()

        window.geometry("919x584")
        window.configure(bg = "#FFFFFF")


        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 584,
            width = 919,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            919.0,
            584.0,
            fill="#C3DD8D",
            outline="")

        canvas.create_text(
            44.0,
            53.0,
            anchor="nw",
            text="Insomnia",
            fill="#597D0D",
            font=("Gluten Medium", 32 * -1)
        )

        canvas.create_rectangle(
            29.0,
            102.0,
            876.0,
            103.03292846679688,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            11.0,
            144.0,
            anchor="nw",
            text='''
            Mindfulness meditation consists of slow, steady breathing while sitting quietly. You observe 
            your breath, body, thoughts, feelings, and sensations as they rise and pass.
            ''',
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            21.0,
            228.0,
            anchor="nw",
            text='''
            Mindfulness meditation has numerous health benefits that go hand-in-hand with a healthy 
            lifestyle promoting good sleep. It's said to reduce stress, improve concentration, and boost 
            immunity.
            ''',
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )

        canvas.create_text(
            21.0,
            336.0,
            
            anchor="nw",
            text='''
            Regular intake of a cup of warm milk with some Ganthoda Powder mixed in it is known to help
            induce sleep.''',
            fill="#384B0F",
            font=("Taviraj", 18 * -1)
        )
        window.resizable(False, False)
        window.mainloop()

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=window_6,
    relief="flat"
)
button_11.place(
    x=402.0,
    y=429.0,
    width=201.0,
    height=38.0
)

canvas.create_text(
    30.0,
    101.0,
    anchor="nw",
    text='''
    Home remedies offer cures with 
    simple, ingredients such as honey,
    fruits, herbs and natural oils. They, 
    at times, can cure common ailments 
    with no side effects, but they need 
    to be used judiciously. Now there is 
    more awareness about the benefits 
    of such remedies as we realise 
    that many of these home remedies 
    have a scientific background, 
    as well. Home Ayurveda brought 
    us many remedies to many ailments 
    and we tried to collect some of 
    them and present here.''',
    fill="#000000",
    font=("Taviraj", 17 * -1)
)

canvas.create_rectangle(
    21.0,
    86.0,
    327.0,
    87.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    672.0,
    305.0,
    anchor="nw",
    text="INVIROGRATIN DRINKS",
    fill="#2B962F",
    font=("Inter Light", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
